<!DOCTYPE html>
<?php
$palmdownloadserver="23.4.17.24"
?>
<html class="js" lang="en-US">
<head>
<link rel="stylesheet" type="text/css" href="assets/widget103.css" media="all">

<meta name="generator" content="TYPO3 4.5 CMS">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="description" content="SDK-PDK Download">
<meta name="keywords" content="Develop, Tools, SDK, PDK">
<meta name="created" content="15.09.2011 20:35:27">
<meta name="modified" content="15.09.2011 21:16:29">
<meta name="robots" content="index, follow">
<meta name="MSSmartTagsPreventParsing" content="true">
<meta name="MSThemeCompatible" content="no">
<meta name="imagetoolbar" content="false">

<link rel="stylesheet" type="text/css" href="assets/stylesheet_5d370599a3.css" media="all">
<!--[if lt IE 7]> <link rel="stylesheet" type="text/css" href="/content/typo3conf/ext/palm_template/css/ie6.1301600288.css" media="all"> <![endif]-->
<!--[if IE 7]> <link rel="stylesheet" type="text/css" href="/content/typo3conf/ext/palm_template/css/ie7.1301600288.css" media="all"> <![endif]-->
<!--[if IE 8]> <link rel="stylesheet" type="text/css" href="/content/typo3conf/ext/palm_template/css/ie8.1301600288.css" media="all"> <![endif]-->
<!--[if IE 9 ]> <link rel="stylesheet" type="text/css" href="/content/typo3conf/ext/palm_template/css/ie9.1301600288.css" media="all"> <![endif]-->
<!--[if gt IE 9 ]><link rel="stylesheet" type="text/css" href="/content/typo3conf/ext/palm_template/css/common.1301600288.css" media="all"><![endif]--><!--[if !IE]><!--> <link rel="stylesheet" type="text/css" href="assets/common.css" media="all"> <!--<![endif]-->
<link rel="stylesheet" type="text/css" href="assets/additional.css" media="screen">

<script src="assets/javascript_343c9f04e8.js" type="text/javascript"></script>

<title> SDK-PDK Download - HP webOS Developer Center</title>			<link rel="shortcut icon" href="https://web.archive.org/web/20130130211140im_/https://developer.palm.com/content/typo3conf/ext/palm_template/icons/favicon.ico" type="application/x-empty; charset=binary">
			<link rel="icon" href="https://web.archive.org/web/20130130211140im_/https://developer.palm.com/content/typo3conf/ext/palm_template/icons/favicon.ico" type="application/x-empty; charset=binary">
<div style="visibility: hidden; height: 1px; width: 1px; position: absolute; z-index: 100000;" id="_atssh"><iframe id="_atssh752" title="AddThis utility frame" style="height: 1px; width: 1px; position: absolute; z-index: 100000; border: 0px none; left: 0px; top: 0px;" src="//web.archive.org/web/20130130212305/http://ct5.addthis.com/static/r07/sh111.html#"></iframe></div><script type="text/javascript" src="assets/core062.js"></script><script src="assets/ga.html" async="true"></script><script type="text/javascript" src="assets/core062.js"></script></head>
<body class="PageArticle">

<!-- Chrome -->
<div class="page-bg-ext"></div><div id="header">
    <div id="header_inner">
        <div class="hp-center">
            <a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/home.html" id="logo"><img src="assets/logo24.png" alt="Palm Developer Center" width="227" height="41"></a>

            <ul class="hp-nav" id="nav"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase.html" title="Showcase" target="_top" class="top">Showcase</a><div class="megamenu">
              <div class="nav-child"><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html" target="_top">Why webOS</a></h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html" target="_top">The Opportunity</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html#item2" target="_top">Innovative Platform</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html#item3" target="_top">Cross-Platform</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html#item5" target="_top">Vibrant Community</a></li></ul></div>
              <div class="nav-child"><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase.html" target="_top">Showcase</a></h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/app_showcase.html" target="_top">App Showcase</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/developer_voices.html" target="_top">Developer Voices</a></li></ul></div>
            </div></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/index.php?option=com_appsubmission&amp;view=applist" title="My Apps" target="_top" class="top">My Apps</a></li><li class="current"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources.html" title="Resources" target="_top" class="top">Resources</a><div class="megamenu">
              <div class="nav-child"><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/design_resources.html" target="_top">Design</a></h4>
                <ul class="nav-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/design/design-enyo.html">Enyo Design Guide</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/advanced_application_guidelines.html" target="_top">Advanced Application Guidelines</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/hp_webos_and_game_development.html" target="_top">webOS and Game Development</a></li></ul><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/development_resources.html" target="_top">Development</a></h4>
                <ul class="nav-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/sdk_pdk_download.html" target="_top">Download the SDK</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/dev-guide/enyo/enyo-basics-from-the-bottom-up.html">Enyo from the Ground Up</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/dev-guide/enyo/tutorial.html">Enyo Tutorial</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/third_party_tools.html" target="_top">Third-party Tools</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/pdk_overview.html" target="_top">PDK Development</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/developing_on_an_unactivated_device.html" target="_top">Unactivated Devices</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/footer/glossary.html" target="_top">Glossary</a></li></ul><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/device_showcase.html" target="_top">Device Specs</a></h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/device_showcase.html" target="_top">View All</a></li></ul></div>
              <div class="nav-child"><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribution_and_promotion_resources.html" target="_top">Distribution and Promotion</a></h4>
                <ul class="nav-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/developing_and_distributing_with_hp/developer_program_details.html" target="_top">Distributing with HP</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/application_content_criteria.html" target="_top">App Content Criteria</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/application_checklist.html" target="_top">App Submission Checklist</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/distribution_international_e_commerce.html" target="_top">International e-commerce FAQ</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/submitting_your_enyo_app.html" target="_top">Submit Your Enyo App</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/app_marketing_kit.html" target="_top">Market Your App</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/promo_codes.html" target="_top">Promo codes</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/managing_in_app_purchase_items.html" target="_top">In-App Purchase</a></li></ul><h4 class="menu-heading">FAQs</h4>
                <ul class="nav-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/faq.html" target="_top">Developer Program FAQ</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/pdk_technical_faq.html" target="_top">PDK Technical FAQ</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/distribution_international_e_commerce.html" target="_top">International e-commerce FAQ</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/where_can_i_distribute_my_apps.html" target="_top">Countries List</a></li></ul><h4 class="menu-heading"><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos.html" target="_top">Videos</a></h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos.html" target="_top">View All</a></li></ul></div>
            </div></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/community.html" title="Community" target="_top" class="top">Community</a><div class="megamenu">
              <div class="nav-child"><h4 class="menu-heading">Connect</h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/distribution/index.php">Forums</a></li><li><a href="https://web.archive.org/web/20130130211140/http://developer.palm.com/blog" target="_blank">Developer Blog</a></li><li><a href="https://web.archive.org/web/20130130211140/http://twitter.com/webosdev" target="_blank">Twitter</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/community/irc.html" target="_top">IRC</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/rss_feeds.html" target="_top">RSS</a></li></ul></div>
              <div class="nav-child"><h4 class="menu-heading">Resources</h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/community/certified_developer_list.html" target="_top">Certified Developers</a></li><li><a href="https://web.archive.org/web/20130130211140/http://github.com/palm" target="_blank">webOS on github</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/distribute/custom_feeds/custom_feeds.html" target="_top">Guide to Custom Feeds</a></li><li><a href="https://web.archive.org/web/20130130211140/http://webos101.com/Main_Page" target="_blank">webOS101 (external)</a></li></ul><h4 class="menu-heading">Community Sites</h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/http://www.mobspot.com/" target="_blank">mobspot</a></li><li><a href="https://web.archive.org/web/20130130211140/http://www.cyrket.com/m/palm/" target="_blank">Cyrket</a></li><li><a href="https://web.archive.org/web/20130130211140/http://www.precentral.net/" target="_blank">PreCentral</a></li><li><a href="https://web.archive.org/web/20130130211140/http://apps.webosroundup.com/" target="_blank">webOS Roundup</a></li></ul></div>
            </div></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/index.html" title="Documentation" target="_top" class="top">Documentation</a><div class="megamenu">
              <div class="nav-child"><h4 class="menu-heading">SDK Documentation</h4>
                <ul class="nav-list last"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/index.html">Index</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/dev-guide.html">Developer Guide</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/api/reference.html">API Reference</a></li></ul></div>
              <div class="nav-child"></div>
            </div></li></ul>
            <div class="attachment">
                <div class="signup">
            <a class="account-text ctx-first" href="https://web.archive.org/web/20130130211140/https://developer.palm.com/index.php?option=com_user&amp;view=login&amp;login">Sign In</a>
            <a class="account-text" href="https://web.archive.org/web/20130130211140/https://developer.palm.com/index.php?option=com_user&amp;view=login&amp;signup">Sign Up</a>
          </div>
                <form class="hp-search" action="https://web.archive.org/web/20130130211140/http://www.palm.com/us/search/developer.html" method="get">
			<fieldset>
				<legend><span>Search Form</span></legend>
				<button class="sifr ext-sifr-search" type="submit">
                	<span>Search</span>
              	</button>
              	<input class="search-txt" name="search" placeholder="Just Search">
              	<input value="all" id="basic-search-collection" type="hidden">
			</fieldset>
		</form>
            </div>
        </div>
    </div>
</div>

<div id="main" class="clearfix two-columns-right">

<div id="intro">
    <ol class="hp-breadcrumbs"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/home.html" target="_top" onfocus="blurLink(this);">Home</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources.html" target="_top" onfocus="blurLink(this);">Resources</a></li><li class="ctx-last">SDK-PDK Download</li></ol>
    <h1 class="page-title">SDK-PDK Download</h1>
    <ul class="inline-icon-list"><li><a onclick="window.print(); return false;" href="javascript: void(0);" class="icon-print">Print</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/sdk_pdk_download.html" target="_top" class="icon-mail addthis_button_email at300b" title="Email"><span class="at16nc at300bs at15nc at15t_email at16t_email"><span class="at_a11y">Share on email</span></span>Email</a></li><li class="last"><div class="addthis_toolbox addthis_default_style"><a class="icon-share addthis_button_compact at300m" href="#"><span class="at16nc at300bs at15nc at15t_compact at16t_compact"><span class="at_a11y">More Sharing Services</span></span>Share</a><div class="atclear"></div></div></li></ul>
</div>

<!-- Actual Content Starts Here -->
<div id="content" class="col-content">
    

    <div class="default-content article-content"><a id="c19192"></a><div class="csc-textpic-text"><h2 class="intro">Developing with the Eclipse™ IDE </h2>
<p class="intro">HP provides plug-ins to the Eclipse IDE to facilitate webOS application development. Eclipse is a popular Integrated Development Environment (IDE) that is applicable to many languages and programming techniques. Eclipse's architecture allows plug-ins to provide custom capabilies within the IDE. The Palm plug-in adds the capability to create app and scene frameworks automatically, and to load and run the app on either a device or the emulator.</p>
<p class="intro">Prior to installing Eclipse and the plug-ins, you need to install the HP webOS SDK and the webOS emulator. If you have not done this yet, go to the SDK download page and click on &quot;Download SDK&quot; to be taken to the correct page for your platform. Be sure to follow the instructions in order, or the emulator may not work correctly. </p>
<p class="bodytext">This document contains the following sections: </p><ul class="def-list"><li>     <a href="#InstallingEclipsewiththeSDK-InstallingEclipseandthePlugIns">Installing Eclipse and the webOS Plug-In     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-InstallingAptanaPlugIn">Installing the Aptana Plug-In     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-UsingEclipsewiththePlugIns">Using Eclipse with the Plug-Ins     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-StayUpdated">Stay Updated     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-dev_mode">Enabling Developer Mode     </a>   </li>  </ul></div><a id="c19202"></a><h2>Installing Eclipse and the webOS Plug-In </h2><div class="csc-textpic-text"><p class="bodytext">This section describes how to install and update Eclipse. </p></div><a id="c19212"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>If you are using an earlier version of Eclipse, you must upgrade to Eclipse 3.5 at minimum to get the new plug-ins for webOS development.</p> 						</div> 					</div></div>
<a id="c19222"></a><h5>Install Eclipse   </h5><div class="csc-textpic-text"><ol><li>Download the latest version of Eclipse <a href="http://eclipse.org/downloads/" target="_blank">here</a>. The correct version is Eclipse IDE for JavaScript Web Developers. Download the appropriate version for your operating system and extract to any location. Eclipse will run from the extracted folder.</li><li>Start Eclipse.</li>      <li>When prompted for a workspace location, accept the default (     /home/YOUR_USER_NAME/workspace     )        </li>  </ol></div><a id="c19232"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>The workspace location must be an absolute path with no spaces.</p> 						</div> 					</div></div>
<a id="c19242"></a><h5>Find and install updates   </h5><div class="csc-textpic-text"><ol><li>Select      <strong>Help &gt; Install New Software</strong>.</li>      <li>In the <strong>Available Software</strong> dialog, click      <strong>Add...</strong></li>      <li>In the      <strong>Location     </strong> field, type&nbsp;http://<?php echo $_SERVER['HTTP_HOST']; ?>/EclipsePlugin/site.xml, and then click      <strong>OK.</strong> (If you are unable to connect to this site, see the Local download instructions below.)<strong> </strong></li>      <li>Open the new site in the list, expand      <strong>Palm webOS SDK</strong>, and the click the      <strong>Palm webOS SDK     </strong> check box.</li>      <li>Click      <strong>Install... &nbsp; &nbsp;&nbsp;</strong> and accept the license agreements.</li><li>When the <strong>Install</strong> dialog comes up, make sure Palm webOS SDK is selected, and click <strong>Finish</strong>.</li>      <li>Restart Eclipse when prompted.</li>  </ol></div><a id="c19252"></a><h2>Installing the Aptana Plug-In </h2><div class="csc-textpic-text"><p class="bodytext">To improve the development experience, HP recommends installing the    <a href="http://www.aptana.com/">Aptana Studio   </a> plug-in.  The Aptana plug-in provides HTML, JavaScript, and CSS functionality to Eclipse.  
</p>
<p class="bodytext">To install Aptana after installing Eclipse, go to    <a href="http://www.aptana.com/" target="_blank">www.aptana.com</a> and Click on the &quot;Download Aptana Studio 3&quot; link. On the &quot;Download&quot; page, select &quot;Eclipse Plug-in Version&quot; and then follow the instructions given.<a name="InstallingEclipsewiththeSDK-UsingEclipsewiththePlugIns" title="InstallingEclipsewiththeSDK-UsingEclipsewiththePlugIns"></a>   </p></div><a id="c19262"></a><h2>Using Eclipse with the Plug-Ins </h2><div class="csc-textpic-text"><p class="bodytext">This section describes how to run Eclipse and use the debug launch configuration. </p></div><a id="c19272"></a><h3>Starting Eclipse </h3><div class="csc-textpic-text"><p class="bodytext">Follow these instructions to start Eclipse:  </p><ul><li>Linux: At the command prompt, type      eclipse</li>      <li>Mac: In the Eclipse folder (inside the Applications folder), double-click      <strong>Eclipse</strong></li>      <li>Windows: Find and open          eclipse.exe      (its location depends on where you installed Eclipse)</li>  </ul></div><a id="c19282"></a><h3>Selecting the webOS Perspective </h3><div class="csc-textpic-text"><p class="bodytext">Eclipse has several perspectives, or views, from which to choose. You want to work in the webOS perspective.</p></div><a id="c19292"></a><h5>Select the perspective   </h5><div class="csc-textpic-text"><ol><li>Select      <strong>Window &gt; Open Perspective &gt; Other...</strong></li>      <li>Select      <strong>webOS</strong>, and then click      <strong>OK</strong></li>  </ol></div><a id="c19302"></a><h3>Generating a webOS Application </h3><div class="csc-textpic-text"><p class="bodytext">This section includes the following procedures: </p><ul><li>     <a href="#InstallingEclipsewiththeSDK-CreateApp">Create a new webOS application     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-AddScene">Add a scene to the application     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-StartApp">Start the application     </a>   </li>      <li>     <a href="#InstallingEclipsewiththeSDK-DebugApp">Debug an application     </a>   </li>  </ul></div><a id="c19312"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>You can also use the New Mojo application icon in the Workbench toolbar to create an application or scene.</p> 						</div> 					</div></div>
<a id="c19322"></a><h5>Create a new webOS application   </h5><div class="csc-textpic-text"><ol><li>Select      <strong>File &gt; New &gt; Basic Application</strong></li>      <li>In the      <strong>Project Name     </strong> field, type a name and the following:          <ul><li>Title        </li>              <li>Vendor       </li>              <li>Id        </li>              <li>Version       </li>          </ul></li>      <li>Click      <strong>Finish</strong></li>  </ol></div><a id="c19332"></a><h5>Add a scene to the application   </h5><div class="csc-textpic-text"><ol><li>Select      <strong>File &gt; New &gt; Basic Scene</strong></li>      <li>Select the project</li>      <li>In the      <strong>Name     </strong> field, type the name of the scene, and then click      <strong>Finish</strong></li>  </ol></div><a id="c19342"></a><h5>Start the application   </h5><div class="csc-textpic-text"><ol><li>Select      <strong>Run &gt; Run Configurations...</strong></li>      <li>Select      <strong>Mojo Application</strong>, and then click the      <strong>New launch configuration     </strong> icon.</li>      <li>In the      <strong>Name     </strong> field, type the name.</li>      <li>Click the      <strong>Project     </strong> arrow to select the project.</li>      <li>Click the      <strong>Target     </strong> arrow and select one of the following:          <ul><li>         <strong>Palm Emulator</strong>, if you are using the emulator.</li>              <li>         <strong>Palm Device</strong>, if you are using a device (ensure the device is in          Developer Mode).</li>          </ul></li>      <li>Click      <strong>Run.</strong></li>  </ol></div><a id="c19352"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>A launch shortcut is also available. Select the project and <strong>Run &gt; Run As &gt; Mojo Application</strong>. If you previously created a launch configuration, that target is used. Otherwise, a dialog box pops up so you can select a target.</p> 						</div> 					</div></div>
<a id="c19362"></a><h5>Debug an application </h5><div class="csc-textpic-text"><ol><li>Select      <strong>Run &gt; Debug Configurations.</strong></li>      <li>Select      <strong>Mojo Application</strong>, and then click the      <strong>New launch configuration     </strong> icon.</li>      <li>In the      <strong>Name     </strong> field, type the name.</li>      <li>Click the      <strong>Project     </strong> arrow to select the project.</li>      <li>Click the      <strong>Target     </strong> arrow and select one of the following:     <ul><li>         <strong>Palm Emulator</strong>, if you are using the emulator.</li>            <li>         <strong>Palm Device</strong>, if you are using a device.</li>        </ul></li>         <li>In the      <strong>Debug Options     </strong> area, select one of the following:     <ul><li>         <strong>Inspectable</strong>, which makes the application's DOM available to the Palm Inspector. This is equivalent to the following command:<br/><pre>palm-launch -i &lt;appid&gt;</pre>              </li>            <li>         <strong>Mojo debugging</strong>, which enables debug logging in the Mojo framework. This is equivalent to the following command:<br/><pre>palm-launch -p &quot;{mojoConfig: {debuggingEnabled:true}}&quot;&lt;appid&gt;</pre></li>        </ul></li>         <li>Click      <strong>Debug.</strong></li>     </ol></div><a id="c19372"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>A launch shortcut is also available. Select the project and <strong>Run &gt; Debug As &gt; Mojo Application</strong>. If you previously created a launch configuration, that target is used. Otherwise, a dialog box pops up so you can select a target.</p> 						</div> 					</div></div>
<a id="c19382"></a><h2>Stay Updated </h2><div class="csc-textpic-text"><p class="bodytext">When new Eclipse plug-ins are available (currently you are notified through email), you can install them through the Eclipse Update Manager as follows: </p><ol><li>Select      <strong>Help &gt; Check for Updates</strong>.</li>      <li>Select      <strong>Palm webOS SDK     </strong> and click      <strong>Update...</strong></li>      <li>Click      <strong>Install     </strong> and accept the license agreements.</li>      <li>Restart Eclipse when prompted.</li>  </ol></div><a id="c19392"></a><h2>Enabling Developer Mode   </h2><div class="csc-textpic-text"><p class="bodytext">To install and test applications on a HP webOS device, you need to enable Developer mode on the device. </p></div><a id="c19402"></a><div class="note notes"><div class="inner"> 						<div class="content"> 							<h4>Note:</h4> 							 							<p>Locking the phone with a PIN does not protect data on the device in Developer mode. When Developer mode is enabled, it is possible to use tools such as novaterm to access the device through the USB even if the phone is locked.</p> 						</div> 					</div></div>
<a id="c19412"></a><h3>Enable Developer mode, webOS 1.0-1.4.5    </h3><div class="csc-textpic-text"><ol><li>In Card view or in the Launcher application, type the following:          <div class="inline_code">upupdowndownleftrightleftrightbastart     </div>      </li>      <li>Tap the resulting      <strong>Developer Mode Enabler     </strong> icon.   </li>      <li>In the application, move the      <strong>Developer Mode     </strong> slider to the      <strong>On     </strong> position.   </li>      <li>Tap      <strong>Reset the Device     </strong>.     <br/> When reset is complete, Developer mode is enabled.   </li>  </ol></div><a id="c19422"></a><h3>Enable Developer mode, webOS 2.0 and 3.0</h3><div class="csc-textpic-text"><ol><li>Go to the phone app.&nbsp;</li><li>On a GSM phone, press &quot;#*DEVMODE#&quot;, followed by the call button. On a CDMA phone or the TouchPad, press &quot;##DEVMODE#&quot;. (If the device is GSM, and there is no SIM card, a screen may be displayed instructing you to install one. Just begin typing the &quot;#*&quot; and the phone app will appear.) </li><li>The Developer Mode scene will be displayed.</li><li>Select &quot;On&quot;. You will be prompted to re-boot the device. </li></ol><p class="bodytext">Note that the DEVMODE code is only for unactivated devices. It provides a way of bypassing activation and first use, and putting the device into developer mode at the same time.
</p>
<p class="bodytext">If you are using an activated device, from card view (that is, no apps active), type the following (from the TouchPad, click in the Just Type area to bring up the virtual keyboard):
</p>
<p class="bodytext">&nbsp;</p><pre>upupdowndownleftrightleftrightbastart</pre><p class="bodytext">&nbsp;</p>
<p class="bodytext">Alternatively, you can use:
</p>
<p class="bodytext">&nbsp;</p><pre>webos20090606</pre><p class="bodytext">&nbsp;</p>
<p class="bodytext">The &quot;Developer Mode&quot; app will come up. Toggle Developer Mode to &quot;On&quot;. The app will dim for a moment, and then Developer Mode will be set. </p></div></div>

    

</div>

<!-- Actual Content Ends Here -->

<!-- Content Nav Starts Here -->
<div class="col-aside">
    <div class="sidebox">
        <h3>Contents</h3>
        <ol class="article-nav"><li class="current last"><a href="/web/20131031072322/https://developer.palm.com/content/resources/develop/developing_with_the_eclipse_ide.html" target="_top">Developing with the Eclipse IDE</a><ol class="level-1"><li><a href="#c19202" target="_top">Installing Eclipse and the webOS Plug-In</a></li><li><a href="#c19222" target="_top">Install Eclipse</a></li><li><a href="#c19242" target="_top">Find and install updates</a></li><li><a href="#c19252" target="_top">Installing the Aptana Plug-In</a></li><li><a href="#c19262" target="_top">Using Eclipse with the Plug-Ins</a></li><li><a href="#c19272" target="_top">Starting Eclipse</a></li><li><a href="#c19282" target="_top">Selecting the webOS Perspective</a></li><li><a href="#c19292" target="_top">Select the perspective</a></li><li><a href="#c19302" target="_top">Generating a webOS Application</a></li><li><a href="#c19322" target="_top">Create a new webOS application</a></li><li><a href="#c19332" target="_top">Add a scene to the application</a></li><li><a href="#c19342" target="_top">Start the application</a></li><li><a href="#c19362" target="_top">Debug an application</a></li><li><a href="#c19382" target="_top">Stay Updated</a></li><li><a href="#c19392" target="_top">Enabling Developer Mode</a></li><li><a href="#c19412" target="_top">Enable Developer mode, webOS 1.0-1.4.5</a></li><li class="last"><a href="#c19422" target="_top">Enable Developer mode, webOS 2.0 and 3.0</a></li></ol></li></ol>
    </div>
</div>
<!-- Content Nav Ends Here -->

</div>

<div id="footer">
    <div class="hp-center">
        <div class="line">
        <div class="unit sizeFooter1">
          <h4 class="aside-heading">Why webOS</h4>
          <ul class="footer-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/why_webos.html" target="_top">Business Case for webOS</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/developer_voices.html" target="_top">Success Stories</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/showcase/app_showcase.html" target="_top">App Showcase</a></li><li><a href="javascript:linkTo_UnCryptMailto('iwehpk6lzyWlwhi:yki');">Contact Us</a></li></ul>
        </div>
        <div class="unit sizeFooter2">
          <h4 class="aside-heading">Getting Started</h4>
          <ul class="footer-list highlight-footer-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/index.php?option=com_user&amp;view=login&amp;signup" target="_blank">Join the HP webOS Developer Program</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/sdk_pdk_download.html" target="_top">Download the SDK/PDK</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/building_your_first_app.html" target="_top">Developing Your First App</a></li></ul>
        </div>
        <div class="unit sizeFooter3">
          <h4 class="aside-heading">Videos</h4>
          <ul class="footer-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos/webos_connect.html" target="_top">webOS CONNECT Events</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos/webos_app_developer_conference.html" target="_top">MWC Developer Conference</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos/palm_developer_day_ny_2010.html" target="_top">NYC Developer Day</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/videos/videos/developer_podcast_series.html" target="_top">Podcasts</a></li></ul>
        </div>
        <div class="unit sizeFooter4">
          <h4 class="aside-heading">Support</h4>
          <ul class="footer-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/footer/help.html" target="_top">Help</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/develop/faq.html" target="_top">FAQs</a></li></ul>
        </div>
        <div class="unit lastUnit">
          <div class="footer-resources">
          <h4 class="aside-heading">Stay up to date</h4>
          <ul class="footer-list rss-list"><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/resources/rss_feeds.html" target="_top">About RSS Feeds</a></li><li><a href="https://web.archive.org/web/20130130211140/http://developer.palm.com/blog" target="_blank">Developer Blog</a></li></ul>
        </div>
        </div>
      </div>
      <div class="imprint clearfix">
        <div class="hp-copyright"><div id="c28323" class="csc-default"><p class="bodytext">© 2011 Hewlett-Packard Development Company, L.P.<br> The information contained herein is subject to change without notice. All screen images simulated. &nbsp;<a href="https://web.archive.org/web/20130130211140/http://www.palm.com/us/company/privacy.html" target="_blank">Privacy Statement</a>
</p>
<p class="bodytext">Supported&nbsp;browsers: Firefox 3.6+; Google Chrome 10+; Safari 5+; Internet Explorer 8+</p></div></div>
        <ul class="inline-footer-list"><li><a href="https://web.archive.org/web/20130130211140/http://www.palm.com/" target="_top" title="Palm.com">Palm.com</a></li><li><a href="https://web.archive.org/web/20130130211140/http://www.palm.com/us/company/legal.html" target="_top" title="Legal Notices">Legal Notices</a></li><li><a href="https://web.archive.org/web/20130130211140/https://developer.palm.com/content/contact_us.html" target="_top" title="Contact Us">Contact Us</a></li></ul>
      </div>
    </div>
</div>

<!--[if lt IE 7 ]><script src="/content/typo3conf/ext/palm_template/js/libs/dd_belatedpng.js"></script><script> DD_belatedPNG.fix('img, .png_bg'); </script><![endif]-->
<script src="assets/jquery-1.js" type="text/javascript"></script>
<script src="assets/jquery_002.js" type="text/javascript"></script>
<script src="assets/jquery.js" type="text/javascript"></script>
<script src="assets/jquery_004.js" type="text/javascript"></script>
<script src="assets/jquery_003.js" type="text/javascript"></script>
<script src="assets/plugins.js" type="text/javascript"></script>
<script src="assets/script.js" type="text/javascript"></script>
<script src="assets/addthis_widget.js" type="text/javascript"></script>
<script src="assets/javascript_7b66301c44.js" type="text/javascript"></script>




<div id="fancybox-tmp"></div><div id="fancybox-loading"><div></div></div><div id="fancybox-overlay"></div><div id="fancybox-wrap"><div id="fancybox-outer"><div class="fancybox-bg" id="fancybox-bg-n"></div><div class="fancybox-bg" id="fancybox-bg-ne"></div><div class="fancybox-bg" id="fancybox-bg-e"></div><div class="fancybox-bg" id="fancybox-bg-se"></div><div class="fancybox-bg" id="fancybox-bg-s"></div><div class="fancybox-bg" id="fancybox-bg-sw"></div><div class="fancybox-bg" id="fancybox-bg-w"></div><div class="fancybox-bg" id="fancybox-bg-nw"></div><div id="fancybox-content"></div><a id="fancybox-close"></a><div id="fancybox-title"></div><a href="javascript:;" id="fancybox-left"><span class="fancy-ico" id="fancybox-left-ico"></span></a><a href="javascript:;" id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a></div></div></body></html>
